version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/express-app
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 1000
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 1000
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 1000
      runas: root